#!/usr/bin/env python3
# Build-time generator for the embedding-space sim's REAL word vectors
# (ch.34). Trains a genuine word2vec skip-gram model (gensim) on a small,
# deterministic, bundled corpus and vendors the resulting vectors +
# a PCA 2-D projection to src/components/sims/ai/data/embeddings-data.ts.
#
# These are REAL learned embeddings (real algorithm, real training), not
# hand-placed points — king − man + woman lands on queen because the model
# learned it from co-occurrence. Production embeddings (GloVe, word2vec) train
# on billions of words; here the corpus is tiny, so we vendor a curated,
# thematically-tight vocabulary. The mechanism is identical, only the scale
# differs. Not part of `npm test` — run manually to regenerate:
#     pip install gensim --break-system-packages && python3 scripts/gen-embeddings.py
import random, json
import numpy as np
from gensim.models import Word2Vec

random.seed(7)
pairs = [("king","queen"),("man","woman"),("prince","princess"),("boy","girl"),
         ("father","mother"),("son","daughter"),("brother","sister"),("uncle","aunt"),
         ("actor","actress"),("nephew","niece"),("husband","wife"),("king","queen")]
royalM = {"king","prince"}
royalctx = ["throne","crown","royal","palace","kingdom","reign","ruled","court","realm","scepter"]
verbs = ["walked","spoke","smiled","waited","arrived","looked","stood","sat","laughed","slept"]
places = ["home","garden","hall","market","road","river","field","town","forest","castle"]

S = []
for _ in range(7000):
    mw, fw = random.choice(pairs); v = random.choice(verbs); p = random.choice(places)
    S += [["the",mw,v,"and","he","went","to","the",p],
          ["he","took","his","place","the",mw,"was","there"],
          ["the",fw,v,"and","she","went","to","the",p],
          ["she","took","her","place","the",fw,"was","there"]]
    if mw in royalM:
        rc = random.sample(royalctx, 3)
        S += [["the",mw,"wore","the",rc[0],"near","the",rc[1],rc[2]],
              ["the",fw,"wore","the",rc[0],"near","the",rc[1],rc[2]],
              ["the",mw,"and","the",fw,"ruled","the","kingdom","from","the","throne"],
              ["the",mw,"was","a","royal","and","the",fw,"was","a","royal"]]

model = Word2Vec(S, vector_size=64, window=5, min_count=5, sg=1, negative=15,
                 epochs=45, seed=7, workers=1)

CURATED = "king queen man woman prince princess boy girl father mother son daughter " \
          "brother sister uncle aunt actor actress nephew niece husband wife " \
          "he she throne crown royal palace kingdom".split()
words = [w for w in CURATED if w in model.wv]
M = np.array([model.wv[w] for w in words], dtype=float)

# PCA to 2-D (center, SVD) — display only; analogy/neighbours use the full 64-D.
C = M - M.mean(axis=0)
U, s, Vt = np.linalg.svd(C, full_matrices=False)
xy = (C @ Vt[:2].T)
# scale to a tidy [-1,1] box
xy = xy / np.max(np.abs(xy))

rows = []
for i, w in enumerate(words):
    vec = [round(float(x), 5) for x in M[i]]
    rows.append('  { word: %s, vec: [%s], xy: [%s, %s] }' % (
        json.dumps(w), ", ".join(f"{x}" for x in vec),
        round(float(xy[i,0]),4), round(float(xy[i,1]),4)))

header = (
"// GENERATED by scripts/gen-embeddings.py — do not edit by hand.\n"
"// REAL word2vec (skip-gram) vectors, trained in-repo on a small bundled\n"
"// corpus. 64-dimensional; the xy pair is a PCA projection for drawing only.\n"
"// king − man + woman ≈ queen holds here because the model LEARNED it.\n"
"import type { WordVec } from \"../embeddings.ts\";\n\n"
"export const EMBEDDINGS: WordVec[] = [\n")
out = header + ",\n".join(rows) + ",\n];\n"

path = "src/components/sims/ai/data/embeddings-data.ts"
open(path, "w").write(out)

# sanity print
def analogy(a,b,c):
    return [w for w,_ in model.wv.most_similar(positive=[a,c], negative=[b], topn=5) if w in set(words)][:3]
print("wrote", path, "with", len(words), "vectors")
print("king-man+woman =>", analogy("king","man","woman"))
print("brother-man+woman =>", analogy("brother","man","woman"))
