// CHANGED: S19 — meta generator for the lazy-load split.
//
// Emits src/data/curriculumMeta.gen.ts: the LIGHT metadata the always-loaded
// shell (TopBar / Footer / StackMap / PartNode / due-badge) needs, derived
// from curriculum.ts + quizzes.ts. With it, the full content module leaves
// the eager bundle and loads on demand (chapter / review / search pages).
//
//   Regenerate:  npm run meta   (after ANY curriculum/quizzes edit)
//   Drift guard: qa-interactivity.ts imports deriveMeta() from here and
//                fails `npm run verify` / CI when the .gen file is stale.
//
// Erasable-syntax only — runs under node --experimental-strip-types.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { CHAPTERS, PARTS, isStub } from "../src/data/curriculum.ts";
import { QUIZZES } from "../src/data/quizzes.ts";
import { INTERVIEW } from "../src/data/interview.ts";
import { KATAS } from "../src/data/katas.ts";
import { splitKeyPoint } from "../src/lib/utils.ts";
import type { ChapterMeta, Part } from "../src/lib/types.ts";

export type DerivedMeta = {
  parts: Part[];
  chapters: ChapterMeta[];
  quizCount: number;
  interviewCount: number;
  kataCount: number;
};

/** Single source of the curriculum → meta mapping (used by gen AND the qa gate). */
export function deriveMeta(): DerivedMeta {
  const parts: Part[] = PARTS.map((p) => ({
    id: p.id,
    order: p.order,
    name: p.name,
    accent: p.accent,
    tagline: p.tagline,
    blurb: p.blurb,
    ...(p.bossId !== undefined ? { bossId: p.bossId } : {}),
  }));

  const chapters: ChapterMeta[] = CHAPTERS.map((c) => {
    // Mirrors srsCards.ts:chapterCards — kp cards need a back side, then :mm.
    const cardIds: string[] = [];
    if (!isStub(c)) {
      c.keyPoints.forEach((kp, i) => {
        if (splitKeyPoint(kp).back !== "") cardIds.push(`${c.id}:kp${i}`);
      });
      cardIds.push(`${c.id}:mm`);
    }
    return {
      id: c.id,
      part: c.part,
      order: c.order,
      title: c.title,
      tagline: c.tagline,
      stub: isStub(c),
      ...(c.plannedSession !== undefined ? { plannedSession: c.plannedSession } : {}),
      cardIds,
    };
  });

  return {
    parts,
    chapters,
    quizCount: QUIZZES.length,
    interviewCount: INTERVIEW.length,
    kataCount: KATAS.length,
  };
}

function render(meta: DerivedMeta): string {
  const parts = JSON.stringify(meta.parts, null, 2);
  const chapters = JSON.stringify(meta.chapters, null, 2);
  return `// GENERATED by scripts/gen-meta.ts — DO NOT EDIT BY HAND.
// Regenerate after any curriculum/quizzes change:  npm run meta
// (qa-interactivity fails verify/CI when this file is stale.)
//
// Light landing-path metadata: everything the always-loaded shell needs,
// so the full curriculum module can stay out of the eager bundle (S19).
import type { ChapterMeta, Part } from "../lib/types.ts";

export const PARTS_META: Part[] = ${parts};

export const CHAPTERS_META: ChapterMeta[] = ${chapters};

export const QUIZ_COUNT = ${meta.quizCount};
export const INTERVIEW_COUNT = ${meta.interviewCount};
export const KATA_COUNT = ${meta.kataCount};

// ---- helpers (mirror curriculum.ts, meta-typed) ----
export function partMetaById(id: string): Part | undefined {
  return PARTS_META.find((p) => p.id === id);
}
export function chapterMetaById(id: string): ChapterMeta | undefined {
  return CHAPTERS_META.find((c) => c.id === id);
}
export function chaptersMetaOfPart(partId: string): ChapterMeta[] {
  return CHAPTERS_META.filter((c) => c.part === partId).sort((a, b) => a.order - b.order);
}
`;
}

function main(): void {
  const here = dirname(fileURLToPath(import.meta.url));
  const out = join(here, "..", "src", "data", "curriculumMeta.gen.ts");
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, render(deriveMeta()), "utf8");
  console.log(`gen-meta: wrote ${out}`);
}

// Run only when executed directly (qa imports deriveMeta without side effects).
if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) main();
