// Build-time regenerator for the tokenizer-toy's BPE merge table (ch.34).
// Trains real Byte-Pair Encoding on the bundled corpus and writes the vendored
// data/bpe-data.ts. `npm test` (test-ch34) re-trains and asserts the output
// matches, so this file only needs re-running if the corpus changes.
// Run: node --experimental-strip-types scripts/gen-bpe.ts
import { writeFileSync } from "node:fs";
import { trainBpe, encode } from "../src/components/sims/ai/bpe.ts";
import { CORPUS } from "../src/components/sims/ai/data/corpus.ts";

const NUM_MERGES = 300;
const merges = trainBpe(CORPUS, NUM_MERGES);
const body =
  "// GENERATED by scripts/gen-bpe.ts — do not edit by hand.\n" +
  `// Real BPE merges trained on data/corpus.ts (${merges.length} merges).\n` +
  `export const BPE_MERGES: [string, string][] = ${JSON.stringify(merges)};\n`;
writeFileSync(new URL("../src/components/sims/ai/data/bpe-data.ts", import.meta.url), body);

console.log(`wrote bpe-data.ts (${merges.length} merges)`);
for (const w of ["strawberry", "tokenization", "the king"]) {
  console.log(`  ${JSON.stringify(w)} →`, encode(w, merges).map((t) => (t.leadingSpace ? "·" : "") + t.text).join(" "));
}
