// GENERATED by scripts/gen-meta.ts — DO NOT EDIT BY HAND.
// Regenerate after any curriculum/quizzes change:  npm run meta
// (qa-interactivity fails verify/CI when this file is stale.)
//
// Light landing-path metadata: everything the always-loaded shell needs,
// so the full curriculum module can stay out of the eager bundle (S19).
import type { ChapterMeta, Part } from "../lib/types.ts";

export const PARTS_META: Part[] = [
  {
    "id": "p0",
    "order": 0,
    "name": "Orientation",
    "accent": "#94A3B8",
    "tagline": "The map and the toolkit",
    "blurb": "What computer science actually is, how this guide works, and an optional math on-ramp for the climb."
  },
  {
    "id": "p1",
    "order": 1,
    "name": "Information",
    "accent": "#FACC15",
    "tagline": "Everything is bits",
    "blurb": "Numbers, text, pixels and sound as 0s and 1s — and why compression is possible at all.",
    "bossId": "boss-p1"
  },
  {
    "id": "p2",
    "order": 2,
    "name": "The Machine",
    "accent": "#FB923C",
    "tagline": "From electrons to a computer",
    "blurb": "Transistors become gates, gates become circuits that count and remember, and suddenly — a CPU runs your program.",
    "bossId": "boss-p2"
  },
  {
    "id": "p3",
    "order": 3,
    "name": "Code",
    "accent": "#A3E635",
    "tagline": "How humans talk to machines",
    "blurb": "From machine code up the abstraction elevator: languages, compilers, and how million-line systems stay sane.",
    "bossId": "boss-p3"
  },
  {
    "id": "p4",
    "order": 4,
    "name": "Algorithms & Data Structures",
    "accent": "#34D399",
    "tagline": "The art of fast",
    "blurb": "Big-O thinking, the classic structures, sorting, graphs, and the design paradigms behind every clever solution.",
    "bossId": "boss-p4"
  },
  {
    "id": "p5",
    "order": 5,
    "name": "Theory",
    "accent": "#2DD4BF",
    "tagline": "The limits of computation",
    "blurb": "Automata, Turing machines, the halting problem, and P vs NP — what computers provably can and cannot do.",
    "bossId": "boss-p5"
  },
  {
    "id": "p6",
    "order": 6,
    "name": "Operating Systems",
    "accent": "#22D3EE",
    "tagline": "The great illusionist",
    "blurb": "How one machine pretends to be many: processes, virtual memory, files, and the dark art of concurrency.",
    "bossId": "boss-p6"
  },
  {
    "id": "p7",
    "order": 7,
    "name": "Networks",
    "accent": "#38BDF8",
    "tagline": "Computers, together",
    "blurb": "Follow a packet across the planet: layers, routing, TCP's promises, and what really happens when you open a URL.",
    "bossId": "boss-p7"
  },
  {
    "id": "p8",
    "order": 8,
    "name": "Data",
    "accent": "#60A5FA",
    "tagline": "Remembering at scale",
    "blurb": "Databases, indexes and transactions — then many machines: replication, partitions, and the CAP trade-off.",
    "bossId": "boss-p8"
  },
  {
    "id": "p9",
    "order": 9,
    "name": "Security",
    "accent": "#818CF8",
    "tagline": "The adversarial mindset",
    "blurb": "Cryptography from Caesar to TLS, the classic attack classes, and defense in depth.",
    "bossId": "boss-p9"
  },
  {
    "id": "p10",
    "order": 10,
    "name": "Intelligence",
    "accent": "#A78BFA",
    "tagline": "Machines that learn",
    "blurb": "From gradient descent to transformers: how modern AI works, what it can do, and where its limits are.",
    "bossId": "boss-p10"
  },
  {
    "id": "p11",
    "order": 11,
    "name": "Capstone",
    "accent": "#94A3B8",
    "tagline": "The whole picture",
    "blurb": "One grand traversal of the entire stack — keypress to pixel — and where to go next."
  }
];

export const CHAPTERS_META: ChapterMeta[] = [
  {
    "id": "ch0a",
    "part": "p0",
    "order": 1,
    "title": "The Map",
    "tagline": "What computer science actually is, how its ten areas connect, and how to travel this guide — the lens, the bosses, the review",
    "stub": false,
    "cardIds": [
      "ch0a:kp0",
      "ch0a:kp1",
      "ch0a:kp2",
      "ch0a:kp3",
      "ch0a:kp4",
      "ch0a:kp5",
      "ch0a:kp6",
      "ch0a:mm"
    ]
  },
  {
    "id": "ch0b",
    "part": "p0",
    "order": 2,
    "title": "Math toolkit",
    "tagline": "Logic, sets & functions, counting, probability, and induction — the small kit of mathematics that quietly powers every part of computer science",
    "stub": false,
    "cardIds": [
      "ch0b:kp0",
      "ch0b:kp1",
      "ch0b:kp2",
      "ch0b:kp3",
      "ch0b:kp4",
      "ch0b:kp5",
      "ch0b:kp6",
      "ch0b:mm"
    ]
  },
  {
    "id": "ch1",
    "part": "p1",
    "order": 3,
    "title": "Bits & numbers",
    "tagline": "One row of switches, read three different ways, becomes every number a computer knows",
    "stub": false,
    "cardIds": [
      "ch1:kp0",
      "ch1:kp1",
      "ch1:kp2",
      "ch1:kp3",
      "ch1:kp4",
      "ch1:kp5",
      "ch1:kp6",
      "ch1:mm"
    ]
  },
  {
    "id": "ch2",
    "part": "p1",
    "order": 4,
    "title": "Encoding the world",
    "tagline": "Text, color and sound are all just agreements about which number means what",
    "stub": false,
    "cardIds": [
      "ch2:kp0",
      "ch2:kp1",
      "ch2:kp2",
      "ch2:kp3",
      "ch2:kp4",
      "ch2:kp5",
      "ch2:kp6",
      "ch2:mm"
    ]
  },
  {
    "id": "ch3",
    "part": "p1",
    "order": 5,
    "title": "Compression & entropy",
    "tagline": "How to spend fewer bits — and the hard floor, set by information itself, that no trick can cross",
    "stub": false,
    "cardIds": [
      "ch3:kp0",
      "ch3:kp1",
      "ch3:kp2",
      "ch3:kp3",
      "ch3:kp4",
      "ch3:kp5",
      "ch3:kp6",
      "ch3:kp7",
      "ch3:mm"
    ]
  },
  {
    "id": "ch4",
    "part": "p2",
    "order": 6,
    "title": "From electricity to gates",
    "tagline": "One physical trick — a switch controlling a switch — becomes all of logic",
    "stub": false,
    "cardIds": [
      "ch4:kp0",
      "ch4:kp1",
      "ch4:kp2",
      "ch4:kp3",
      "ch4:kp4",
      "ch4:kp5",
      "ch4:kp6",
      "ch4:kp7",
      "ch4:kp8",
      "ch4:kp9",
      "ch4:mm"
    ]
  },
  {
    "id": "ch5",
    "part": "p2",
    "order": 7,
    "title": "Circuits that count",
    "tagline": "Wire gates so the carry flows, and the same silicon that does logic starts doing arithmetic",
    "stub": false,
    "cardIds": [
      "ch5:kp0",
      "ch5:kp1",
      "ch5:kp2",
      "ch5:kp3",
      "ch5:kp4",
      "ch5:kp5",
      "ch5:kp6",
      "ch5:kp7",
      "ch5:kp8",
      "ch5:kp9",
      "ch5:mm"
    ]
  },
  {
    "id": "ch6",
    "part": "p2",
    "order": 8,
    "title": "Circuits that remember",
    "tagline": "Feed a gate's output back into itself and the loop holds a value — the strangest trick in the machine",
    "stub": false,
    "cardIds": [
      "ch6:kp0",
      "ch6:kp1",
      "ch6:kp2",
      "ch6:kp3",
      "ch6:kp4",
      "ch6:kp5",
      "ch6:kp6",
      "ch6:kp7",
      "ch6:kp8",
      "ch6:kp9",
      "ch6:mm"
    ]
  },
  {
    "id": "ch7",
    "part": "p2",
    "order": 9,
    "title": "The CPU",
    "tagline": "Wire the ALU and the registers to a clock-driven control loop, and the pile of circuits becomes a machine that runs your programs",
    "stub": false,
    "cardIds": [
      "ch7:kp0",
      "ch7:kp1",
      "ch7:kp2",
      "ch7:kp3",
      "ch7:kp4",
      "ch7:kp5",
      "ch7:kp6",
      "ch7:kp7",
      "ch7:kp8",
      "ch7:mm"
    ]
  },
  {
    "id": "ch8",
    "part": "p2",
    "order": 10,
    "title": "Fast CPUs",
    "tagline": "The ch.7 loop can't just be clocked faster — so real CPUs overlap it, cache around it, predict past it, and finally replicate it",
    "stub": false,
    "cardIds": [
      "ch8:kp0",
      "ch8:kp1",
      "ch8:kp2",
      "ch8:kp3",
      "ch8:kp4",
      "ch8:kp5",
      "ch8:kp6",
      "ch8:mm"
    ]
  },
  {
    "id": "ch9",
    "part": "p2",
    "order": 11,
    "title": "GPUs & parallel hardware",
    "tagline": "The opposite bet from a CPU — throw away single-thread cleverness for thousands of simple lanes — and why that turned the graphics card into the engine of AI",
    "stub": false,
    "cardIds": [
      "ch9:kp0",
      "ch9:kp1",
      "ch9:kp2",
      "ch9:kp3",
      "ch9:kp4",
      "ch9:kp5",
      "ch9:mm"
    ]
  },
  {
    "id": "ch10",
    "part": "p3",
    "order": 12,
    "title": "From machine code to languages",
    "tagline": "Nobody should write raw opcodes by hand — so we build an elevator of abstractions up from the CPU, and add the one mechanism ch.7 lacked: the call stack",
    "stub": false,
    "cardIds": [
      "ch10:kp0",
      "ch10:kp1",
      "ch10:kp2",
      "ch10:kp3",
      "ch10:kp4",
      "ch10:kp5",
      "ch10:kp6",
      "ch10:mm"
    ]
  },
  {
    "id": "ch11",
    "part": "p3",
    "order": 13,
    "title": "Compilers & interpreters",
    "tagline": "The program that drives the abstraction elevator: source → tokens → tree → bytecode → a running machine, one honest stage at a time",
    "stub": false,
    "cardIds": [
      "ch11:kp0",
      "ch11:kp1",
      "ch11:kp2",
      "ch11:kp3",
      "ch11:kp4",
      "ch11:kp5",
      "ch11:mm"
    ]
  },
  {
    "id": "ch12",
    "part": "p3",
    "order": 14,
    "title": "Software engineering",
    "tagline": "Writing a program is ch.10–11; keeping a million-line system that hundreds of people change every day from collapsing is a different problem — this is how",
    "stub": false,
    "cardIds": [
      "ch12:kp0",
      "ch12:kp1",
      "ch12:kp2",
      "ch12:kp3",
      "ch12:kp4",
      "ch12:kp5",
      "ch12:mm"
    ]
  },
  {
    "id": "ch13",
    "part": "p4",
    "order": 15,
    "title": "Big-O & algorithmic thinking",
    "tagline": "Two programs can both be correct and yet one finishes before lunch while the other outlives the sun — Big-O is how you tell them apart before you ever run them",
    "stub": false,
    "cardIds": [
      "ch13:kp0",
      "ch13:kp1",
      "ch13:kp2",
      "ch13:kp3",
      "ch13:kp4",
      "ch13:kp5",
      "ch13:kp6",
      "ch13:mm"
    ]
  },
  {
    "id": "ch14",
    "part": "p4",
    "order": 16,
    "title": "Linear structures",
    "tagline": "Arrays, linked lists, stacks, queues and hash tables — the containers you reach for a hundred times a day, and the memory-layout reasons each is fast at some things and slow at others",
    "stub": false,
    "cardIds": [
      "ch14:kp0",
      "ch14:kp1",
      "ch14:kp2",
      "ch14:kp3",
      "ch14:kp4",
      "ch14:kp5",
      "ch14:kp6",
      "ch14:mm"
    ]
  },
  {
    "id": "ch15",
    "part": "p4",
    "order": 17,
    "title": "Trees & heaps",
    "tagline": "Bending the line into a hierarchy — search trees that stay balanced under adversarial input, heaps that always surface the smallest, and tries that share prefixes",
    "stub": false,
    "cardIds": [
      "ch15:kp0",
      "ch15:kp1",
      "ch15:kp2",
      "ch15:kp3",
      "ch15:kp4",
      "ch15:kp5",
      "ch15:kp6",
      "ch15:kp7",
      "ch15:mm"
    ]
  },
  {
    "id": "ch16",
    "part": "p4",
    "order": 18,
    "title": "Sorting & searching",
    "tagline": "Binary search's O(log n) reward for keeping data sorted, the classic sorts and how to race them fairly, stability, and why comparison sorts can't beat n log n — but counting and radix can",
    "stub": false,
    "cardIds": [
      "ch16:kp0",
      "ch16:kp1",
      "ch16:kp2",
      "ch16:kp3",
      "ch16:kp4",
      "ch16:kp5",
      "ch16:kp6",
      "ch16:kp7",
      "ch16:mm"
    ]
  },
  {
    "id": "ch17",
    "part": "p4",
    "order": 19,
    "title": "Graphs",
    "tagline": "Any node to any node: representations and their cost, the one traversal loop behind BFS/DFS/Dijkstra/A*, topological order, and minimum spanning trees",
    "stub": false,
    "cardIds": [
      "ch17:kp0",
      "ch17:kp1",
      "ch17:kp2",
      "ch17:kp3",
      "ch17:kp4",
      "ch17:kp5",
      "ch17:kp6",
      "ch17:mm"
    ]
  },
  {
    "id": "ch18",
    "part": "p4",
    "order": 20,
    "title": "Design paradigms",
    "tagline": "The four templates most clever algorithms are instances of — divide & conquer, dynamic programming, greedy, backtracking — and how to tell which a problem wants",
    "stub": false,
    "cardIds": [
      "ch18:kp0",
      "ch18:kp1",
      "ch18:kp2",
      "ch18:kp3",
      "ch18:kp4",
      "ch18:kp5",
      "ch18:kp6",
      "ch18:mm"
    ]
  },
  {
    "id": "ch19",
    "part": "p5",
    "order": 21,
    "title": "Automata & regular languages",
    "tagline": "The simplest machines — finite states, no memory — and the exact boundary of what they can and cannot recognize",
    "stub": false,
    "cardIds": [
      "ch19:kp0",
      "ch19:kp1",
      "ch19:kp2",
      "ch19:kp3",
      "ch19:kp4",
      "ch19:kp5",
      "ch19:mm"
    ]
  },
  {
    "id": "ch20",
    "part": "p5",
    "order": 22,
    "title": "Computability",
    "tagline": "One tape more than an automaton buys the power to compute anything computable — and the first problems no machine can ever solve",
    "stub": false,
    "cardIds": [
      "ch20:kp0",
      "ch20:kp1",
      "ch20:kp2",
      "ch20:kp3",
      "ch20:kp4",
      "ch20:kp5",
      "ch20:mm"
    ]
  },
  {
    "id": "ch21",
    "part": "p5",
    "order": 23,
    "title": "Complexity",
    "tagline": "Among the problems we CAN solve, which can we solve fast — and the million-dollar question of whether checking is really easier than finding",
    "stub": false,
    "cardIds": [
      "ch21:kp0",
      "ch21:kp1",
      "ch21:kp2",
      "ch21:kp3",
      "ch21:kp4",
      "ch21:kp5",
      "ch21:mm"
    ]
  },
  {
    "id": "ch22",
    "part": "p6",
    "order": 24,
    "title": "Processes & scheduling",
    "tagline": "One CPU, many programs — how the OS fakes a computer for each of them, and decides who runs next",
    "stub": false,
    "cardIds": [
      "ch22:kp0",
      "ch22:kp1",
      "ch22:kp2",
      "ch22:kp3",
      "ch22:kp4",
      "ch22:kp5",
      "ch22:kp6",
      "ch22:mm"
    ]
  },
  {
    "id": "ch23",
    "part": "p6",
    "order": 25,
    "title": "Memory",
    "tagline": "Every process is told it owns all of memory, alone, from address zero — and hardware keeps the lie true on every single access",
    "stub": false,
    "cardIds": [
      "ch23:kp0",
      "ch23:kp1",
      "ch23:kp2",
      "ch23:kp3",
      "ch23:kp4",
      "ch23:kp5",
      "ch23:kp6",
      "ch23:mm"
    ]
  },
  {
    "id": "ch24",
    "part": "p6",
    "order": 26,
    "title": "Files & storage",
    "tagline": "Above, a file is a clean, named, growable array of bytes; below, it's scattered blocks on a disk that can crash mid-write — and the OS keeps the story straight",
    "stub": false,
    "cardIds": [
      "ch24:kp0",
      "ch24:kp1",
      "ch24:kp2",
      "ch24:kp3",
      "ch24:kp4",
      "ch24:kp5",
      "ch24:kp6",
      "ch24:mm"
    ]
  },
  {
    "id": "ch25",
    "part": "p6",
    "order": 27,
    "title": "Concurrency",
    "tagline": "The moment two flows of execution touch the same memory at once, 'obviously correct' code isn't — and the worst failure is everyone politely waiting for each other forever",
    "stub": false,
    "cardIds": [
      "ch25:kp0",
      "ch25:kp1",
      "ch25:kp2",
      "ch25:kp3",
      "ch25:kp4",
      "ch25:kp5",
      "ch25:kp6",
      "ch25:mm"
    ]
  },
  {
    "id": "ch26",
    "part": "p7",
    "order": 28,
    "title": "How networks work",
    "tagline": "No shared memory, an unreliable wire, billions of machines — and yet a packet you send finds one exact server on the far side of the planet in milliseconds",
    "stub": false,
    "cardIds": [
      "ch26:kp0",
      "ch26:kp1",
      "ch26:kp2",
      "ch26:kp3",
      "ch26:kp4",
      "ch26:kp5",
      "ch26:kp6",
      "ch26:mm"
    ]
  },
  {
    "id": "ch27",
    "part": "p7",
    "order": 29,
    "title": "TCP & UDP",
    "tagline": "IP promises nothing — packets drop, duplicate, and arrive out of order. TCP turns that shrug into a promise you can build a bank on, using only acknowledgements and a clock",
    "stub": false,
    "cardIds": [
      "ch27:kp0",
      "ch27:kp1",
      "ch27:kp2",
      "ch27:kp3",
      "ch27:kp4",
      "ch27:kp5",
      "ch27:kp6",
      "ch27:mm"
    ]
  },
  {
    "id": "ch28",
    "part": "p7",
    "order": 30,
    "title": "The Web",
    "tagline": "Type a URL, press Enter, and in a few hundred milliseconds a dozen protocols you never see collaborate to turn a name into pixels — the most-used layer of the whole stack",
    "stub": false,
    "cardIds": [
      "ch28:kp0",
      "ch28:kp1",
      "ch28:kp2",
      "ch28:kp3",
      "ch28:kp4",
      "ch28:kp5",
      "ch28:kp6",
      "ch28:mm"
    ]
  },
  {
    "id": "ch29",
    "part": "p8",
    "order": 31,
    "title": "Databases",
    "tagline": "A table you can query by saying what you want, an index that finds one row among millions in a handful of page reads, and a transaction that keeps its promises even when the power fails",
    "stub": false,
    "cardIds": [
      "ch29:kp0",
      "ch29:kp1",
      "ch29:kp2",
      "ch29:kp3",
      "ch29:kp4",
      "ch29:kp5",
      "ch29:kp6",
      "ch29:kp7",
      "ch29:kp8",
      "ch29:mm"
    ]
  },
  {
    "id": "ch30",
    "part": "p8",
    "order": 32,
    "title": "Distributed systems",
    "tagline": "Spread the data across many machines for scale and survival — and discover that with no shared clock and a network that can split, even 'is this value the latest?' becomes a genuine choice",
    "stub": false,
    "cardIds": [
      "ch30:kp0",
      "ch30:kp1",
      "ch30:kp2",
      "ch30:kp3",
      "ch30:kp4",
      "ch30:kp5",
      "ch30:kp6",
      "ch30:kp7",
      "ch30:mm"
    ]
  },
  {
    "id": "ch31",
    "part": "p9",
    "order": 33,
    "title": "Cryptography",
    "tagline": "The math that lets strangers keep secrets and prove identity over a wire everyone can read — from Caesar's shift to the handshake behind every padlock icon",
    "stub": false,
    "cardIds": [
      "ch31:kp0",
      "ch31:kp1",
      "ch31:kp2",
      "ch31:kp3",
      "ch31:kp4",
      "ch31:kp5",
      "ch31:kp6",
      "ch31:kp7",
      "ch31:kp8",
      "ch31:mm"
    ]
  },
  {
    "id": "ch32",
    "part": "p9",
    "order": 34,
    "title": "Security",
    "tagline": "Cryptography is a strong lock — security is realizing the attacker will use the window; the adversarial mindset, the attack classes that actually breach systems, and defense in depth",
    "stub": false,
    "cardIds": [
      "ch32:kp0",
      "ch32:kp1",
      "ch32:kp2",
      "ch32:kp3",
      "ch32:kp4",
      "ch32:kp5",
      "ch32:kp6",
      "ch32:kp7",
      "ch32:kp8",
      "ch32:mm"
    ]
  },
  {
    "id": "ch33",
    "part": "p10",
    "order": 35,
    "title": "Machine learning",
    "tagline": "The shift from writing rules to learning them from data: features, loss, gradient descent, the neuron that becomes a network, and the discipline that separates learning from memorizing",
    "stub": false,
    "cardIds": [
      "ch33:kp0",
      "ch33:kp1",
      "ch33:kp2",
      "ch33:kp3",
      "ch33:kp4",
      "ch33:kp5",
      "ch33:kp6",
      "ch33:mm"
    ]
  },
  {
    "id": "ch34",
    "part": "p10",
    "order": 36,
    "title": "Modern AI & frontiers",
    "tagline": "From word vectors to transformers to large language models: how attention, tokenization, and scale turned next-token prediction into general-seeming intelligence — and where its hard limits still are",
    "stub": false,
    "cardIds": [
      "ch34:kp0",
      "ch34:kp1",
      "ch34:kp2",
      "ch34:kp3",
      "ch34:kp4",
      "ch34:kp5",
      "ch34:mm"
    ]
  },
  {
    "id": "ch35",
    "part": "p11",
    "order": 37,
    "title": "The whole picture",
    "tagline": "One keystroke traced through every layer you built — bit, gate, CPU, process, program, packet, cipher, stored row, model, pixel — the whole of computer science in a single causal chain, plus the frontier beyond it",
    "stub": false,
    "cardIds": [
      "ch35:kp0",
      "ch35:kp1",
      "ch35:kp2",
      "ch35:kp3",
      "ch35:kp4",
      "ch35:kp5",
      "ch35:mm"
    ]
  }
];

export const QUIZ_COUNT = 38;
export const INTERVIEW_COUNT = 193;
export const KATA_COUNT = 74;

// ---- helpers (mirror curriculum.ts, meta-typed) ----
export function partMetaById(id: string): Part | undefined {
  return PARTS_META.find((p) => p.id === id);
}
export function chapterMetaById(id: string): ChapterMeta | undefined {
  return CHAPTERS_META.find((c) => c.id === id);
}
export function chaptersMetaOfPart(partId: string): ChapterMeta[] {
  return CHAPTERS_META.filter((c) => c.part === partId).sort((a, b) => a.order - b.order);
}
